### ISSUE TITLE
libssh2 don't support windows XP

### ISSUE THREAD

**Issue by WeMissing** [libssh2/libssh2#1274]
**Describe the bug**
libssh2 is dependent on bcrypt.dll file in Win32; it's throw error When I run it in Windows XP ;because the bcrypt.dll file is missing in Windows XP

**To Reproduce**
Run the sftp example in Windows XP.

**Version (please complete the following information):**
 - OS and version: Windows XP
 - libssh2 version: 1.11.0
 - crypto backend and version: OpenSSL 1.1.1

**Additional context**
It still throw error when I copy bcrypt.dll file from windows 7 to Windows XP

**Comment by vszakats** [comment]
I double checked and libssh2 doesn't use `bcrypt` for anything else than WinCNG. It does need however bcrypt header and implib to be present _at build time_, because some builds of OpenSSL/LibreSSL do actually need this. Old mingw is known to be missing this, other compilers should work fine.

`bcrypt` is only linked to libssh2 if it's actually needed by OpenSSL/LibreSSL. If it isn't, the linker doesn't link to `bcrypt.dll` ("as-needed" is the default linking mode on Windows), and thus should run on XP.

Please comment or reopen if you find something that I missed.
