### ISSUE TITLE
scp function (Windows) through OpenSSH  (for Windows as well)

### ISSUE THREAD

**Issue by littlegene** [libssh2/libssh2#139]
# I successfully use scp (say, scp.c example: example-scp.exe) in Windows to work with legacy linux sshd to upload or download any files. But when I use a recent Windows server instead (approx. github/PowerShell/Win32-OpenSSH/releases...) I can't.

The matter is that libssh2 can only succeed if the file name to download (or upload) is quoted ( ' '). And consequently, I can't access files from any paths (except for user's main directory: C:\Users\myuser).

Example:
I want to download file named **file1** from default user directory C:\Users\myuser.
I launch:
example-scp.exe host myuser password file1
, I fail.
If I rename file1 on the server to 'file1', I succeed.

On the contrary when I use example-scp_write.exe executable build from libssh2 example directory, the result of the upload is: C:\Users\myuser\'localfile', instead of (C:\Users\myuser\localfile)
I suspect we should dig something like shell_quotearg routine from scp.c source, but I am afraid I can't handle with it on my own. If not, probably,  the trouble is tiny but I anyway -- do not know how to resolve it.;-(

p.s. 
scp.exe utility from native OpenSSH deployment works well.

Note : there is no such a problem with sftp protocol.
eg: example-sftp_write.exe host myuser password localfile "С:\Users\myuser\somedir\destfile"
succeeds.
Unfortunately, I am facing the necessity to involve the SCP protocol features from my usage of libssh2.
Looking forward to hear for a suggestion.

**Comment by littlegene** [comment]
Note : there is no such a problem with sftp protocol.
eg: example-sftp_write.exe host myuser password localfile "С:\Users\myuser\somedir\destfile"
succeeds.
Unfortunately, I am facing the necessity to involve the SCP protocol features from my usage of libssh2. 
Looking forward to hear for a suggestion.

**Comment by salva** [comment]
This is a tricky issue. SCP file transfers work by launching the remote `scp` command on the remote side using the `exec` mechanism as is done for regular commands. That means that the `scp` command line is processed by the remote user shell (shell metacharacters are processed, variables expanded, etc.).

In order to avoid the shell metacharacter processing, libssh2 escapes the paths when the `scp` command line is composed but, unfortunately, there is no way to escape those paths in a portable way (every shell uses a different set of rules). libssh2 has picked the POSIX rules which are compatible with `bash`, `ksh` and most commonly used Unix/Linux shells, but not with Windows `cmd.exe` shell or the `CreateProcess` function call.

AFAIK, there is currently no way to fix the quoting in the implementation of SCP in libssh2 but that could be fixed by a brave soul!

An easy solution would be to add support for a `no_quote` flag in `scp_send` that would make it skip the path quoting (client code should take the responsibility of doing it then).

A more difficult solution would be to extend `scp_send` to support several quoting rule sets and let the user pick the right one.

Well, actually both approaches are compatible... the `no_quoting`, could be considered as just another type of shell.

Note also that there are some operating systems/shells (for instance VMS/DCL) whose command line arguments can not be quoted in a generic way without interacting with the shell.

**Comment by salva** [comment]
BTW, could you expand why you can not use SFTP? There are not too many operations (if any) that can be done with SCP but not with SFTP.

**Comment by littlegene** [comment]
Thanks for your reply! No problems for now.)
Just there were my first steps in using development libraries to download very big files from an already established (for other purposes) ssh-server. Of course I managed to touch on the SCP source to force appropriate behaviour with that, non-cygwin, ssh-server, the bottleneck was a bit faster speed than SFTP case for an old 586 hardware of server. But it suddenly turned out *no security* (no crypto, no compression, no hash calc) obligate,  so the development has migrated to other, fast and efficient client development and server software tools.
