### ISSUE TITLE
Patch to allow public-key from memory

### ISSUE THREAD

**Issue by doublex** [libssh2/libssh2#143]
This patch fixes three issues:
a) Allow to pass a password to an in-memory private-key
b) Add missing "mbedtls_rsa_init()"
c) "int mbedtls_pk_parse_key()" checks in "mbedtls/pkparse.c:1074" if the last byte of the privatekey is null: `key[keylen - 1] != '\0'`
So one has to pass the null-terminator to mbed-tls. "libssh2" needs the null-terminator anyways because libssh2 ignores the length parameter of "libssh2_userauth_publickey_frommemory()" and calls "strlen()"

``` diff
*** mbedtls.c-old       2016-10-26 14:10:16.755031650 +0200
--- mbedtls.c   2016-10-26 16:08:13.474135845 +0200
*************** _libssh2_mbedtls_rsa_new_private_frommem
*** 374,383 ****
      if (*rsa == NULL)
          return -1;

      mbedtls_pk_init(&pkey);

!     ret = mbedtls_pk_parse_key(&pkey, (unsigned char *)filedata,
!                               filedata_len, NULL, 0);
      if( ret != 0 || mbedtls_pk_get_type(&pkey) != MBEDTLS_PK_RSA)
      {
          mbedtls_pk_free(&pkey);
--- 374,388 ----
      if (*rsa == NULL)
          return -1;

+     mbedtls_rsa_init(*rsa, MBEDTLS_RSA_PKCS_V15, 0);
      mbedtls_pk_init(&pkey);

!     if (passphrase != NULL)
!         ret = mbedtls_pk_parse_key(&pkey, (unsigned char *)filedata,
!                                   filedata_len + 1, passphrase, strlen((const char *)passphrase));
!     else
!         ret = mbedtls_pk_parse_key(&pkey, (unsigned char *)filedata,
!                                   filedata_len + 1, NULL, 0);
      if( ret != 0 || mbedtls_pk_get_type(&pkey) != MBEDTLS_PK_RSA)
      {
          mbedtls_pk_free(&pkey);
*************** _libssh2_mbedtls_pub_priv_keyfilememory(
*** 591,598 ****
      int ret;

      mbedtls_pk_init(&pkey);
!     ret = mbedtls_pk_parse_key(&pkey, (unsigned char *)privatekeydata,
!                               privatekeydata_len, NULL, 0);
      if( ret != 0 )
      {
          mbedtls_strerror(ret, (char *)buf, sizeof(buf));
--- 596,607 ----
      int ret;

      mbedtls_pk_init(&pkey);
!     if (passphrase != NULL)
!         ret = mbedtls_pk_parse_key(&pkey, (unsigned char *)privatekeydata,
!                                   privatekeydata_len + 1, passphrase, strlen((const char *)passphrase));
!     else
!         ret = mbedtls_pk_parse_key(&pkey, (unsigned char *)privatekeydata,
!                                   privatekeydata_len + 1, NULL, 0);
      if( ret != 0 )
      {
          mbedtls_strerror(ret, (char *)buf, sizeof(buf));
```

**Comment by alamaison** [comment]
Could you open a Pull Request with this patch?  It makes it hard to review like this and even harder to merge

**Comment by doublex** [comment]
@alamaison - I have never used git/svn/... (beside cloning). It is not the right tool for me

**Comment by alamaison** [comment]
Using git is not hard and definitely worthwhile learning for the future.  I'm happy to talk you through it.

The basic procedure is:

- Fork the libssh2/libssh2 repo from the github interface
- Clone (checkout) your fork: `git clone git@github.com:doublex/libssh2.git` or `https://github.com/doublex/libssh2.git`
- Make your changes to the local copy
- Mark the the changes as ready for committing `git add -u`
- Commit the changes locally `git commit -m "Sentence describing the changes"`
- Push the changes to your remove repo `git push origin master`
- Go to https://github.com/libssh2/libssh2
- The page will ask you whether you want to make a pull request from your pushed version
- Make the pull request
- Done

There's quite a few steps but none of the steps are complicated.  The reason for so many steps is so that you can do more advanced things along the way as you get more proficient.

**Comment by doublex** [comment]
@alamaison 
Thanks!
I tried to create 4 pull requests - but the later contains all previous commits....

**Comment by alamaison** [comment]
Sorry, I gave you a shortened version of the instructions to keep things simple.  But I forgot you needed to make multiple PRs in parallel.  Your combined PR is fine, but for the future the way to create PRs in parallel is to make you changes on a new git branch (`git checkout -b my_branch_name`) and push that branch to github instead of pushing master
