### ISSUE TITLE
Segfault using ssh-agent on Windows

### ISSUE THREAD

**Issue by alexcrichton** [libssh2/libssh2#162]
Originally reported https://github.com/rust-lang/cargo/issues/3401 it looks like the segfault in that issue comes from libssh2. Unfortunately there's a lot of layers of indirection to how it's used. Cargo (the Rust language's package manager) uses git2-rs, bindings for libgit2 in Rust. Then libgit2 itself is using libssh2 under the hood. Right now we've only seen this issue on Windows, not on other platforms yet.

There's some stack traces in the [last comment](https://github.com/rust-lang/cargo/issues/3401#issuecomment-267794703) on that issue, and I've verified that the segfault reproduces at the current head commit (f7daf3185a4e889fcd5272858db97764a279da1e) of libssh2. It looks like the segfault [happens here](https://github.com/libssh2/libssh2/blob/f7daf3185a4e889fcd5272858db97764a279da1e/src/wincng.c#L1992) because `bn->bignum` is NULL. That function is in turn [called here](https://github.com/libssh2/libssh2/blob/f7daf3185a4e889fcd5272858db97764a279da1e/src/kex.c#L143) during `diffie_hellman_sha1`, [called here](https://github.com/libssh2/libssh2/blob/f7daf3185a4e889fcd5272858db97764a279da1e/src/kex.c#L1472) in `kex_method_diffie_hellman_group14_sha1_key_exchange`, which I believe itself originates [here](https://github.com/libssh2/libssh2/blob/f7daf3185a4e889fcd5272858db97764a279da1e/src/kex.c#L2550).

I do realize that this is unfortunately not a huge amount to go off, but I'm hoping that someone with more knowledge than I could recognize something here and perhaps spot the bug! If it helps the program is trying to connect to `github.com` over SSH with the username `git`, and the ssh-agent itself was set up with `eval $(ssh-agent)`.

If any more information is needed I can certainly try to help provide it!

**Comment by bagder** [comment]
I don't know this code at all and since wincng is involved, it seems very windows specific.

I checked a few lines above kex.c:143 on line 136 where it seems 'e' is being generated (which is the field that later contains the NULL). This function call to `libssh2_dh_key_pair()` ignores the return code but when checking the wincng code for `_libssh2_dh_key_pair()` it calls `_libssh2_wincng_bignum_mod_exp()` that has several code branches where it returns failure instead of being successful. A guess of mine is that one of them happens in this error case but since nothing catches the error in the parent functions, the kex code doesn't know and continues when it should in fact already have exited out gracefully with some error.

**Comment by alexcrichton** [comment]
@bagder I think your diagnosis is spot on!

I stepped through the code in a debugger, and sure enough [this call](https://github.com/libssh2/libssh2/blob/master/src/wincng.c#L1917-L1919) to `BCryptImportKeyPair` failed which was then ignored.

**Comment by alexcrichton** [comment]
I tested out [this patch](https://gist.github.com/alexcrichton/beb732c3245c0b8edd7aa80eb5a3ee0b) locally and it does indeed resolve the segfault issue, returning an error all the way back up, going back to the [original behavior](https://github.com/rust-lang/cargo/issues/3401#issue-195446967) of everything failing with a nice error!

@bagder if you'd like I can send a PR with those or similar changes, but if you already have a fix in mind feel free to do that instead.

**Comment by bagder** [comment]
Lovely! Please submit as a PR and I'll give it some attention!
