### ISSUE TITLE
fails: SCP with >2GB files on Windows

### ISSUE THREAD

**Issue by bagder** [libssh2/libssh2#30]
Originally reported in https://github.com/bagder/curl/issues/329 by @rivy.

See https://github.com/libssh2/libssh2/blob/master/src/libssh2_priv.h#L794 and https://github.com/libssh2/libssh2/blob/master/src/scp.c#L690

On Windows (in particular) we cannot store and use file sizes as a 'long' to deal with >2GB files.

**Comment by bagder** [comment]
See also #31

**Comment by jay** [comment]
See also curl/curl#858

**Comment by vszakats** [comment]
I'm now creating a test build with `HAVE_STRTOI64` option enabled manually. By the look of it, this seems important, and not enabled by default when building using `makefile.m32`.

**Comment by vszakats** [comment]
This fixed it. So the root cause was that I was using `makefile.m32`-based build, which doesn't automatically enable this build flag and I didn't enable it manually either when upgrading to 1.7.0.

Fix landed here: https://github.com/vszakats/harbour-deps/commit/204b0b033d5501e5f02866bf55f7c16f33d6248b
New binaries will be ready in 30 minutes.

**Comment by rivy** [comment]
@bagder , this is fixed. You can close this issue.

**Comment by bagder** [comment]
thanks for telling, case closed!
