### ISSUE TITLE
Visual Studio project is corrupt

### ISSUE THREAD

**Issue by primis** [libssh2/libssh2#427]
Attempted to open the win32/libssh2 workspace in both Microsoft Visual Studio 2010 and 2019. Both complained:
"The project file 'libssh2-master\win32\libssh2.dsp' has been corrupted and cannot be opened" (Path shortened for privacy)

**Comment by tiennou** [comment]
The CMake buildsystem should have a working Visual Studio generator, which was able to open and build libssh2 — at least it did the last time I tried, so YMMV.

I wasn't aware there was a need for a working VS workspace, so maybe this file should be removed in favor of the CMake generator ? Personally I'm already only caring about CMake anyways, since I have .xcodeproj files with it, the Automake stuff borks tarballs, etc.

**Comment by tsengjun** [comment]
CMake will take care VS solution file version difference. Have a try to CMake.
That libssh2.dsw was 10 years old, obviously not up to date.

**Comment by primis** [comment]
This did in fact work for me, CMake generated VS solution and it built no problems.
I would suggest removing libssh2.dsw from the repository since it won't be of much use to anyone
-- Closing issue
