### ISSUE TITLE
Support the ChaCha20-Poly1305 cipher

### ISSUE THREAD

**Issue by eccgecko** [libssh2/libssh2#507]
Please could you include support for the ChaCha20-Poly1305 cipher. It is a secure cipher developed by Daniel Berstein, and includes both encryption and authentication, so no need for MACs.

It has been included in OpenSSH for some time, and in libssh since [2018](https://www.libssh.org/2018/08/10/libssh-0-8-0/)

**Comment by willco007** [comment]
I have this implemented in a private fork. The issue is it's not a super clean implementation so I haven't submitted a PR. The transport read function of libssh2 assumes block based packet decryption but some modern techniques work on the entire packet. Transport read needs to be refactored to handle this cleanly but it's not a trivial task so I haven't made time to do it. This refactor is also needed for clean ETM support.
