### ISSUE TITLE
Question: is there a release plan for next version?

### ISSUE THREAD

**Issue by youknowone** [libssh2/libssh2#572]
Hi, I am not urging at all, but just in curious.

One of library I am using is depending on `libssh2_channel_request_auth_agent` which is contributed in 2019.
And the latest release was done a bit ago from then.

Will there be a release soon including the change? or would it be better to suppose it will take time and build my own version for a while?

**Comment by willco007** [comment]
Yes, master is stable, we just need to wrap up a formal release.

**Comment by StefanKarpinski** [comment]
With full acknowledgment that asking open source projects for a release timeline is fraught (don't I know it?) any rough idea what kind of timeframe this might happen on so that we can plan accordingly? Is this on the order of weeks, months, years?

**Comment by jonhoo** [comment]
@willco007 Gentle nudge on this — do you have a rough timeline for when you might be able to cut a new release?

**Comment by youknowone** [comment]
hey bot, seriously?

**Comment by StefanKarpinski** [comment]
Stalebot is the worst. The @JuliaLang project is also very interested in whether there will be a new release fixing known security issues. If there isn't, we will have to discontinue using libssh2 and libgit2 since it would be irresponsible to keep using a software stack that has known insecurities.

**Comment by willco007** [comment]
1.10.0 has been released.
