### ISSUE TITLE
libssh2_userauth_publickey_fromfile_ex reports "Authentication failed" when private keys are in RFC4716 format

### ISSUE THREAD

**Issue by campbsb** [libssh2/libssh2#631]
**Describe the bug**
libssh2_userauth_publickey_fromfile_ex  cannot read OpenSSH RSA private keys stored in the default RFC4716 format. However, rather than reporting that it cannot understand the file, we simply get a misleading authentication failed error.

Converting the file to the older PEM format fixes the issue.

See https://github.com/php/pecl-networking-ssh2/blob/RELEASE_1_2/ssh2.c#L692

**To Reproduce**
Convert an existing authorized RSA key to RFC4716 format:
ssh-keygen -p -m RFC4716 id_rsa

and use it to connect

**Expected behavior**
a) Be updated to be able to read  RFC4716 format
b) Return a more descriptive warning if it cannot understand the file format

**Comment by kdkasad** [comment]
The `libssh2_userauth_publickey_fromfile_ex` function does actually return `LIBSSH2_ERROR_FILE` when it can't read the keyfile. However this is not documented, it's just what I've discovered from testing.

**Comment by willco007** [comment]
When using the OpenSSL backend, Libssh2 supports the proprietary, and to my knowledge, default OpenSSH key format which uses the header `-----BEGIN OPENSSH PRIVATE KEY-----`. RFC 4716 seems to predate the format change.

**Comment by vszakats** [comment]
This [commit](https://github.com/libssh2/libssh2/commit/03092292597ac601c3f9f0c267ecb145dda75e4e) landed "OpenSSH Key format reading support", released in libssh2 v1.9.0. We also have an OpenSSH RSA [key](https://github.com/libssh2/libssh2/blob/f2de2fda4e0cc314465ed00e59a541627f5d3ca4/tests/key_rsa_openssh) in our default test suite. According `ssh-keygen` man page, that format is RFC4716.

We also merged this [commit](https://github.com/libssh2/libssh2/commit/097c8f0dae558643d43051947a1c35b65e1c5761) that improves the error message when using OpenSSL 3.

These suggest the problem has been solved since. Please reopen if this still applies to the recent master branch.
